name: Discord-MCPE
author: Niekert
version: "1.0.3"
api: [4.9.0]
softdepend: PurePerms
main: Niekert\DiscordMCPE\Main
commands:
    discord:
        description: Send an message to Discord!
        permission: discord.send
        usage: /discord MESSAGE
        aliases: [dc]
permissions:
    discord.send:
        default: op
